:icons: font
:experimental:
:source-highlighter: rouge
:rouge-css: style

= Refactoring to Patterns

In this tutorial, we will use https://naomod.univ-nantes.io/sce/slides/refactorings.html[refactoring] operations to apply design patterns to improve code maintainability.

To build the project, you need Apache Maven, JDK 11 (or greater) and IntelliJ.
IntelliJ IDEA is *mandatory* to follow the tutorial.

Refactoring is an activity that improves the design of a software source code.
During this activity, developers use specific set of source code transformations, named *refactoring operations*.
Refactoring operations are simple code changes that preserve the visible behavior of a program.

[WARNING]
====
During this tutorial--as well as when refactoring source code--you must follow two rules:

. All Unit Tests must always pass, before and after code changes
. The build must always pass and never crash

If you break one of these rules, you should *stop* refactoring and *revert* your changes.
====

== Getting Ready

IMPORTANT: Before starting this tutorial, you *must* fork and clone this repository.

. On this https://gitlab.univ-nantes.fr/naomod/sce/refactoring-to-patterns[project] click on https://gitlab.univ-nantes.fr/naomod/sce/refactoring-to-patterns/-/forks/new[Fork] to create a fork of the project in your account.

. Clone your project and open it with IntelliJ.

. In the project root, add a document named `CONTRIBUTORS.md`, add your name to it, commit and push your changes.

. *Do not* make your project private, otherwise it will become invisible for the instructors.

== Introduce Compose Method

In this first exercise, we will simplify a simple method that adds elements to an array of objects.

The "Compose
Method"footnote:[http://c2.com/ppr/wiki/WikiPagesAboutRefactoring/ComposedMethod.html]
pattern is about producing methods that efficiently communicate what
they do and how they do what they do. According to Kent Beck:

[cite, Kent Beck]
____
«Divide your program into methods that perform one identifiable task.
Keep all of the operations in a method at the same level of abstraction.
This will naturally result in programs with many small methods, each a
few lines long.»
____

A Composed Method consists of calls to well-named methods that are all
at the same level of detail. 
Follow the instructions below to simplify the method `add()` from class `ArrayList`:

This class is available link:./src/main/java/fr/rtp/util/ArrayList.java[here].

.The ArrayList Class
[source,java]
----
include::src/main/java/fr/rtp/util/ArrayList.java[]
----

The `ArrayList` class is composed of three parts:

<1> The _read only_ check part
<2> The grow part
<3> The actual add behavior part

=== Guard Clauses

[quote]
____
A guard clause is simply a check (the inverted `if`) that immediately exits the function, either with a `return` statement or an exception. Using guard clauses, the possible error cases are identified and there is the respective handling by returning or throwing an adequate exception.
____

TIP: For more information about Guard Clauses, read the refactoring https://refactoring.guru/fr/replace-nested-conditional-with-guard-clauses[Replace Nested Conditinal with Guard Clauses].

.To-Do
****
. Invert the "readonly"  check to introduce a "Guard Clause".
. Run all tests and check that they still pass after the changes.
+
[source,sh]
----
mvn clean test
----

. Commit and push your changes
+
[source,shell]
----
git stage ./src/main/java/fr/rtp/util/ArrayList.java
git commit -m "Replace Nested Conditional with Guard Clause"
git push
----
****


=== Extract Private Method

Apply the _Extract Method_ refactoring operation to replace the two lines that actually add an element and create the private method `void addElement(Object obj)`.

.To-Do
****
. Use the _Extract Method_ refactoring from IntelliJ
.. Select the lines you want to place in a different method.
.. Go to menu:Refactor[Extract/Introduce > Method...] and name the new method `addElement()`.
. Run all tests and check that they still pass after the changes.
. Commit and push your changes
****

=== Replace Magic Numbers

Apply the _Extract Constant_ refactoring operation to replace the magic number `10` and introduce an "Explanatory Variable" named `GROWTH_INCREMENT`.

[quote, Kent Beck]
____
Explanatory variables are variables with meaningful names, which held intermediate values of complex calculations to break them up.

The simple use of explanatory variables makes it clear that the first matched group is the key, and the second matched group is the value.
____

.To-Do
****
. Use the _Extract Constant_ refactoring operation from IntelliJ
.. Select the value (`10`)
.. Go to menu:Refactor[Extract/Introduce > Constant...] and name the new constant `GROWTH_INCREMENT`.
. Run all tests and check that they still pass after the changes.
. Commit and push your changes
****

=== Extract Private Method Again

Replace the boolean expression of the `if` statement by a method call that explains the expression:
it checks whether the `element`  array is at its capacity and needs to grow.

.To-Do
****
. Inline variable `newSize`.
.. Inside the if condition, click on variable `newSize`.
.. Go to menu:Refactor[Inline Variable].

. Extract Method
.. Select the boolean expression inside the if condition
.. Go to menu:Refactor[Extract/Introduce > Method...] and name the new method `atCapacity()`.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes
****

=== Extract the `grow()` Method

Finally, apply the __Extract Method__ refactoring operation to the part of the code that grows the size of the array, creating the `grow()` private method.

.To-Do
****
. Extract method
.. Select the statements inside the *if true* bloc.
.. Go to menu:Refactor[Extract/Introduce > Method...] and name the new method `grow()`.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes
****

=== Final code

After applying all the previous refactoring operations, your code should look like:

[source,java]
----
public void add(Object child) {
    if (readOnly) {
        return;
    }
    if (atCapacity()) {
        grow();
    }
    addElement(child);
}
----

== Replace Conditional Logic with Strategy

The https://naomod.univ-nantes.io/patterns/strategy.html[Strategy Design Pattern] defines a family of algorithms, encapsulates each algorithm, and make them interchangeable, letting the algorithm vary independently of the clients that use it.

We can apply this pattern to classes where several methods have similar structure: a sequence of similar conditions.

For instance, let us consider the `Loan`
classfootnote:[http://www.informit.com/articles/article.aspx?p=1398607&seqNum=2],
from Joshua Kerievsky’s book <<rtp>>:

The `Loan` class is available link:./src/main/java/fr/rtp/loan/Loan.java[here].

[source,java]
----
include::src/main/java/fr/rtp/loan/Loan.java[]
----

This class deals with calculating capital for three different kinds of bank loans:

Term loan::
A loan from a bank for a specific amount that has a specified repayment schedule and a fixed or floating interest rate.
Revolver::
A credit that is automatically renewed as debts are paid off.
Advised line::
A credit that a financial institution approves and maintains for a customer.

Much of the logic of methods and deals with figuring out whether the loan is a term loan, a revolver, or an advised line.

For example, a `null` expiry date and a non-`null` maturity date indicate a term loan.
A `null` maturity and a non-`null` expiry date indicate a revolver loan.

In this exercise, we will use the Strategy Design Pattern to simplify the calculation of the loan’s capital.

=== Create the `CapitalStrategy` class

.To-Do
****
. Create an empty class named `CapitalStrategy`.
. Add a field named `strategy` to class `Loan`.
+
[source, java]
.The empty `CapitalStrategy`class and its usage
----
public class CapitalStrategy {}
public class Loan {
    private CapitalStrategy strategy = new CapitalStrategy();
    // (...)
}
----
. Run all tests and check that they still pass after the changes.
. Commit and push your changes
****

=== Move Field `commitment` to `CapitalStrategy`

We need to move the methods `capital()` and `duration()` from class `Loan` to class `CapitalStrategy`.

To this end, we will need first to move first the fields and auxiliary methods used by these two methods.

[CAUTION]
====
IntelliJ does not implement all known refactoring operations.
In some cases, you need to apply refactoring manually.

*Be careful:* Before changing the source code, think twice!

Ask yourself:
____
Will this change affect the behavior of the source code?
____
====

.To-Do
****
. Select the `commitment` field at its declaration and go to menu:Refactor[Encapsulate Fields...].
.. *Do not* encapsulate the _Set access_  (the field is never modified)
.. Set the _Accessor Visibility_ to `private`.
. icon:hand[] Move the `commitment` field to class `CapitalStrategy`:
.. Cut&Paste the field declaration to move it. Make it `final`.
.. Create a new constructor in class `CapitalStrategy` that initializes field `commitment`. Use menu:Code[New... > Constructor].
.. Move the initialization of field `strategy`, from its declaration to the two constructors. At the same time, remove the initializations of field `commitment`, which no longuer exists.
.. Copy&Paste the accessor method (`getCommitment()`).
.. Change the visibility of the pasted method to `protected`.
.. Make the original method _delegate_ its behavior to the new one.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes

.CapitalStrategy class, after changes
[source,java]
----
public class CapitalStrategy {
    private final double commitment;

    public CapitalStrategy(double commitment) {
        this.commitment = commitment;
    }

    protected double getCommitment() {
        return commitment;
    }
}
----

.Snippet of class Loan, after changes
[source,java]
----
public class Loan {
    private CapitalStrategy strategy;
    public Loan(double commitment, double outstanding, Date start, Date expiry, Date maturity, int riskRating) {
        strategy = new CapitalStrategy(commitment);
        // (...)
    }
    public Loan(double commitment, Date start, Date maturity, int riskRating) {
        strategy = new CapitalStrategy(commitment);
        // (...)
    }
    // (...)
    private double getCommitment() {
        return strategy.getCommitment();
    }
}
----
****

=== Move fields  maturity, expirity, outstanding, riskRating and start to CapitalStrategy

.To-Do
****
. Encapsulate fields `maturity`, `expirity`, `outstanding`, `riskRating` and `start` with a private *get* accessor.

. Cut&Paste the field declarations to move them. Make them `final`.

. Create a new constructor in class `CapitalStrategy` that initializes field `commitment`.
+
[TIP]
====
Delete the old constructor and use menu:Code[New... > Constructor] to create a new one.
====
+
. Move the new  accessor methods to `CapitalStrategy`.

. Change the visibility of the pasted method to `protected`.

. Make the original methods _delegate_ their behavior to the new ones.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes

.CapitalStrategy class after changes
[source,java]
----
public class CapitalStrategy {
    private final double commitment;
    private final double outstanding;
    private final Date maturity;
    private final Date expiry;
    private final Date start;
    private final int riskRating;

    public CapitalStrategy(double commitment, double outstanding, Date maturity, Date expiry,
                           Date start, int riskRating) {
        this.commitment = commitment;
        this.outstanding = outstanding;
        this.maturity = maturity;
        this.expiry = expiry;
        this.start = start;
        this.riskRating = riskRating;
    }

    protected double getCommitment() {
        return commitment;
    }

    protected double getOutstanding() {
        return outstanding;
    }

    protected Date getMaturity() {
        return maturity;
    }

    protected Date getExpiry() {
        return expiry;
    }

    protected Date getStart() {
        return start;
    }

    protected int getRiskRating() {
        return riskRating;
    }
}
----

.Snippet of class Loan, after changes
[source,java]
----
public class Loan {
    public Loan(double commitment, double outstanding, Date start, Date expiry, Date maturity, int riskRating) {
        strategy = new CapitalStrategy(commitment, outstanding, maturity, expiry, start, riskRating);
        payments = new HashSet<Payment>();
    }

    public Loan(double commitment, Date start, Date maturity, int riskRating) {
        strategy = new CapitalStrategy(commitment, commitment, maturity, null, start, riskRating);
        payments = new HashSet<Payment>();
    }
// (...)
    private double getOutstanding() {
        return strategy.getOutstanding();
    }

    private Date getMaturity() {
        return strategy.getMaturity();
    }

    private Date getExpiry() {
        return strategy.getExpiry();
    }

    private Date getStart() {
        return strategy.getStart();
    }

    public int getRiskRating() {
        return strategy.getRiskRating();
    }
}
----
****

=== Move method yearsTo() to CapitalStrategy

.To-Do
****
. icon:hand[] Move, using Cut&Paste, fields `today`, `MILLIS_PER_DAY` and `DAYS_PER_YEAR` to class CapitalStrategy
. icon:hand[]  Copy, using Copy&Paste, method `yearsTo()` to class `CapitalStrategy`.
.. Change the visibility of the new method to `protected`.
. Replace the body of the original method with a delegation to the new method.
. Run all tests and check that they still pass after the changes.
. Commit and push your changes

.Method Loan::yearsTo() after changes
[source,java]
----
private double yearsTo(Date endDate) {
    return strategy.yearsTo(endDate);
}
----

.Method CapitalStrategy::yearsTo() after changes
[source, java]
----
protected double yearsTo(Date endDate) {
    Date beginDate = (today == null ? getStart() : today);
    return ((endDate.getTime() - beginDate.getTime()) / MILLIS_PER_DAY) / DAYS_PER_YEAR;
}
----
****

=== Move method duration() to CapitalStrategy

NOTE: Here we will use a different approach to move a method from one class to another, without using Copy&Paste

.To-Do
****
. Change the visibility of method `weightedAverageDuration()` to `protected`.

. Select all the lines of the body of method `duration()`.

. Go to menu:Refactor[Extract/Introduce > Method...] and extract the new method.
.. Use a temporary name for the method, `extracted()` is just fine.

. Go to menu:Refactor[Move Instance Method] to move the new method to class `CapitalStrategy`.
.. Do not worry about the visibility warnings.

. icon:hand[] Replace `loan` by `this` in the new method, when the method already exists in class `CapitalStrategy`
+
|===
|Replace | by

| `loan.getExpiry()`
| `this.getExpiry()`

| `loan.getMaturity()`
| `this.getMaturity()`

| `loan.yearsTo(loan.getExpiry())`
| `this.yearsTo(this.getExpiry())`
|===

. Select the new method name, go to menu:Refactor[Rename...] and rename it to `duration()`.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes

.Method `Loan::duration()` after changes
[source,java]
----
----
****

=== Move method capital() to CapitalStrategy

.To-Do
****
. Move method `outstandingRiskAmount()`
.. This method has two method calls: `getCommitment()` and `getOutstanding()`.
.. Inline these calls:
... Click on the first method call then go to menu:Refactor[Inline Method...]
... Choose "Inline this only and keep the method"
... Do the same with the second method call.
+
.Method `outstandingRiskAmount()` after inlines
[source,java]
----
private double unusedRiskAmount() {
    return (strategy.getCommitment() - strategy.getOutstanding());
}
----
.. Click on the name of method `outstandingRiskAmount()`.
.. Go to menu:Refactor[Move Instance Method...] and move method to class `CapitalStrategy`.
.. Choose visibility "Escalate" and let IntelliJ choose the appropriate visibility.

. Move method `outstandingRiskAmount()`
.. Inline the only method call
.. Move method to class `CapitalStrategy`.

. Move method `riskFactor()`
.. Inline the method call `getRiskRating()`
.. Move method to class `CapitalStrategy`.

. Move method `unusedRiskFactor()`
.. Inline the method call `getRiskRating()`
.. Move method to class `CapitalStrategy`.

. Move method  `getUnusedPercentage()`
.. Go to menu:Refactor[Move Instance Method...] and move method to `Capital Strategy`

. Finally, move method `capital()`
.. Inline all method calls
+
.Method capital() after inlines and before move
[source, java]
----
public double capital() {
    if (strategy.getExpiry() == null && strategy.getMaturity() != null) // Term Loan
        return strategy.getCommitment() * strategy.duration(this) * strategy.riskFactor();
    if (strategy.getExpiry() != null && strategy.getMaturity() == null) {
        if (strategy.getUnusedPercentage() != 1.0) // Revolver
            return strategy.getCommitment() * strategy.getUnusedPercentage() * strategy.duration(this) * strategy.riskFactor();
        else // Advised Line
return (strategy.outstandingRiskAmount() * strategy.duration(this) * strategy.riskFactor())
+ (this.strategy.unusedRiskAmount() * strategy.duration(this) * strategy.unusedRiskFactor());
    }
    return 0.0;
}
----

.. Select the method body (all method code lines) and go to menu:Refactor[Extract/Introduce > Method]
... Choose a temporary name for the method, for instance `extractedCapital()`
.. Click on the name of the new method and go to menu:Refactor[Move Instance Method...] and move it to class `CapitalStrategy`
.. Rename the new method to `capital()`

. In the end, you should have the following code:
+
.Method Loan::capital() after changes
[source,java]
----
public double capital() {
    return strategy.capital(this);
}
----
+
.Method CapitalStrategy::capital() after changes
[source,java]
----
double capital(Loan loan) {
    if (getExpiry() == null && getMaturity() != null) // Term Loan
        return getCommitment() * duration(loan) * riskFactor();
    if (getExpiry() != null && getMaturity() == null) {
        if (getUnusedPercentage() != 1.0) // Revolver
            return getCommitment() * getUnusedPercentage() * duration(loan) * riskFactor();
        else // Advised Line
            return (outstandingRiskAmount() * duration(loan) * riskFactor())
                    + (unusedRiskAmount() * duration(loan) * unusedRiskFactor());
    }
    return 0.0;
}
----

. Run all tests and check that they still pass after the changes.
. Commit and push your changes
****

=== Replace Conditional with Polymorphism

Now that we migrated methods `capital()` and `duration()` to `CapitalStrategy`, we will create the classes that play the _Concrete Strategy_ roles and move that methods to these classes.

.To-Do
****
. Create the _Concrete Strategy_ classes
.. Create the classes `RevolverStrategy`, `TermLoanStrategy`, and `AdvisedLineStrategy`.
.. Make them subclasses of `CapitalStrategy`.
.. Go to menu:Code[Generate... > Constructor] to add a constructor to these classes.

. Instantiate the correct strategy for a Loan.
.. Modify the constructors of class `Loan` and make them instantiate the correct strategy.
+
[NOTE]
====
According to the code:

* When `expiry` is `null`, the strategy should be "Term Loan".
* When `expiry` is not `null` and `maturity` is `null`, the strategy should be "Revolver".
* Otherwise, the strategy should be "Advised Line".
====

. Make classe `CapitalStrategy` abstract.
. Push down method `capital()`
.. Click on the method name, then go to menu:Refactor[Push Members Down...]
.. Add an abstract method `capital()` to class `CapitalStrategy`.

. Open class `RevolverStrategy` and remove the parts of code that do not concern a revolver loan
+
.Method RevolverStrategy::capital() after changes
[source,java]
----
double capital(Loan loan) {
    return getCommitment() * getUnusedPercentage() * duration(loan) * riskFactor();
}
----

. Open class `TermLoanStrategy` and remove the parts of code that do not concern a revolver loan
+
.Method TermLoanStrategy::capital() after changes
[source,java]
----
double capital(Loan loan) {
    return getCommitment() * duration(loan) * riskFactor();
}
----

. Open class `AdvisedLineStrategy` and remove the parts of code that do not concern a revolver loan
+
.Method AdvisedLineStrategy::capital() after changes
[source,java]
----
double capital(Loan loan) {
    return (outstandingRiskAmount() * duration(loan) * riskFactor())
+ (unusedRiskAmount() * duration(loan) * unusedRiskFactor());
}
----

. Repeat the same operations for method `CapitalStrategy::duration()`

. Run all tests and check that they still pass after the changes.
. Commit and push your changes

****

== Chain Constructors

Classes may have several constructors: this is normal, as there may be
different ways to instantiate objects of a same class.
However, maintenance problems arise when code snippets are duplicated across the code source.

Consider the three constructors of class `BankLoan` presented in listing <<lst:bankloan>>, which have duplicated code.
We will use the refactoring operation named _Chain Constructors_,
whose goal is to remove duplication in constructors by making them call each other.

First, we analyze these constructors to find out which one is the *catch-all constructor*,
the one that handles all the construction details.
It seems that it should be constructor 3,
since making constructors 1 and 2 call 3 can be achieved with a minimum amount of work.

.Class BankLoan
[source#lst:bankloan,java]
----
include::src/main/java/fr/rtp/utilities/chainconstructors/BankLoan.java[]
----

.To-Do
****
. Change constructor 1 to make it call constructor 3.
. Change constructor 2 to make it also call constructor 3.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes

.BankLoan class after changes
[source,java]
----
public class BankLoan {
    // (...)
    public BankLoan(float national, float outstanding, int rating, Date expiry) {
        this(new TermROC(), national, outstanding, rating, expiry, null);
    }

    public BankLoan(float national, float outstanding, int rating, Date expiry, Date maturity) {
        this(new RevolvingTermROC(), national, outstanding, rating, expiry, maturity);
    }

    public BankLoan(BankCapitalStrategy strategy, float national, float outstanding, int rating, Date expiry, Date maturity) {
        this.strategy = strategy;
        this.national = national;
        this.outstanding = outstanding;
        this.rating = rating;
        this.expiry = expiry;
        this.maturity = maturity;
    }
}
----
****

== Replace Constructors with Creation Methods

The goal of the _Replace Constructors with Creation Methods_ refactoring operation is to replace constructors with intention-revealing creation methods that return object instances.

[IMPORTANT]
====
_Creation Method_ is a generic term to designate any method that creates instances of a class.
For instance, the https://refactoring.guru/design-patterns/factory-method[Factory Method] and
the https://refactoring.guru/design-patterns/builder[Builder] Design Patterns use _Creation Methods_.
====

Creation methods have at least two advantages, that cannot be achieved in Java.
First, they can have different names and thus communicate intention efficiently.
Second, different creation methods can have the same number of parameters.

We will apply this refactoring to improve the constructions of class `Loan`.
Consider the source code of this class, presented below.

[source,java]
----
include::src/main/java/fr/rtp/creation/creationmethods/Loan.java[]
----

.To-Do
****
. To apply this refactoring, we need to find a code that calls one of these constructors. For instance, in a test case, such as link:./src/test/java/fr/rtp/creation/creationmethods/CapitalCalculationTest.java[CapitalCalculationTest]

. Create Creation Method
.. Select the code that creates an instance of `Loan`, i.e. `new Loan(commitment,
riskRating, maturity)`
.. Go to menu:Refactor[Extract/Introduce > Method...]. Name the method `createTermLoan()`

. Make it static and public
.. Click on the method name
.. Go to menu:Refactor[Make static...]
.. Make it public
+
.Creation Method createTermLoan()
[source,java]
----
public static Loan createTermLoan(Date maturity, int riskRating, double commitment) {
    return new Loan(commitment, riskRating, maturity);
}
----

. Move method to class `Loan`
.. Click on the method name and go to menu:Refactor[Move Members...]
.. Write down the destination (to) class: `fr.rtp.creation.creationmethods.Loan`.

. After doing that, we will need to find all callers of the constructor and update them to call `createTermLoan()`.
.. Click on the first constructor and then go to menu:Navigate[Declaration or Usages].
.. You you find any usage other than the creation method, make it call `createTermLoan()`.


. Inline method
.. Since now the method is now the only caller on the constructor, we can apply the _Inline Method_ refactoring to this
constructor.
.. Inside the creation method, click on the construction call and then go to menu:Refactor[Inline Method..] choose *Inline all and remove the method*.

. Repeat the same procedure to the other constructors, to create
additional creation methods on class `Loan`.
+
.New Creation Methods
[source,java]
----
public static Loan newRevolver(double commitment, Date start, Date expiry, int riskRating) {
    return new Loan(commitment, 0, start, expiry, null, riskRating, new CapitalStrategyRevolver());
}

public static Loan newAdvisedLine(double commitment, Date start, Date expiry, int riskRating) {
    if (riskRating > 3) return null;
    Loan advisedLine = new Loan(commitment, 0, start, expiry, null, riskRating, new CapitalStrategyAdvisedLine()); advisedLine.setUnusedPercentage(0.1);
    return advisedLine;
}
----

. Last step, since the constructors are only used by creation methods, they can become private.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes
****

== Replace State-Altering Conditionals with State

link:https://www.informit.com/articles/article.aspx?p=1398607&seqNum=4[]

The https://refactoring.guru/design-patterns/state[State] Design Pattern applies to classes whose objet behaviors are strongly dependent on their internal state.

The State Design Pattern encapsulates the behavior specific to each state and replaces conditional checks by delegations.

For instance, let us consider the link:./src/main/java/fr/rtp/simplification/condwithstate/SystemPermission.java[`SystemPermission`] class, from Joshua Kerievsky’s book <<rtp>>:

[source,java]
----
include::src/main/java/fr/rtp/simplification/condwithstate/SystemPermission.java[]
----

The `SystemPermission` plays the role of _Context_ in the State Design Pattern.
It has a state field, i.e. a field that gets assigned to or compared against a family of constants during state transitions.
In this class, the state field is also named `state`.


=== Replace Type Code with Class

At first, we will apply the refactoring operation named https://refactoring.guru/fr/replace-type-code-with-class[Replace Type Code with Class].

We will change the type of the original state field, from `String` to a new class named `PermissionState`.

.To-Do
****
. Create a new class named `PermissionState`.

. Copy the `state` field to `PermissionState` and make it private and final. A value will be set for this field only from the constructor.

. Create a getter for the field.
+
.Class PermissionState, initial version
[source,java]
----
public class PermissionState {
    private final String state;

    public PermissionState(String state) {
        this.state = state;
    }

    public String getState() {
        return state;
    }
}
----

. Move state constants to class `PermissionState`.
.. Click on constant `REQUESTED`, then go to menu:Refactor[Move Members...], and move the constant to class `fr.unantes.sce.temp.PermissionState`.
.. Change the types and the initialization values of the constants `REQUESTED`, `CLAIMED`, `GRANTED`, and `DENIED`.
Each field initialization creates an instance of `PermissionState` corresponding to this value of `state`.
+
[source,java]
.Constant initialization
----
public final static PermissionState REQUESTED = new PermissionState("REQUESTED");
----
. Add methods `equals()` and `hashCode()` to class `PermissionState`.
.. Go to menu:Code[Generate...] and choose "equals() and hashCode()".

. In class `SystemPermission`:
.. Replace the type of field `state` with `PermissionState`.

.. Change the getter of the `state` field, so that it calls the `PermissionState` class getter.

. Run all tests and check that they still pass after the changes.
. Commit and push your changes.
****

=== Extract subclasses

Now, we will apply the refactoring operation named
https://refactoring.guru/fr/extract-subclass[Extract Subclass] to class `PermissionState`.

.To-Do
****
. Create a class, subclass of `PermissionState` for each constant: `Requested`, `Claimed`, etc.
.. After creating each subclass, go to menu:Code[Generate...] and choose "Constructor" to create a constructor.

. Update the constant initialization in class `PermissionState`, so that each refers to the correct subclass instance of
the state superclass.
+
[source,java]
.Constant initialization, updated
----
public final static PermissionState REQUESTED = new Requested("REQUESTED");
----

. Now, declare the state superclass to be abstract.
. Run all tests and check that they still pass after the changes.
. Commit and push your changes.
****

=== Move state-dependent methods

Several methods from class `SystemPermission` implement a behavior that highly depends on the current state: `grantedBy()`, `claimedBy()`, and `deniedBy()`.

We will move these methods to the state classes and replace the original methods by a delegation.

.To-Do
****
. Before moving the methods, we need to prepare the body of these methods, making the used fields and called methods accessible from the state classes.

.. Change the visibility of methods `willBeHandledBy()`, `notifyUserOfPermissionRequestResult()`, and `notifyAdminOfPermissionRequest()` to `package-local` or `protected`.

.. Encapsulate field `state`. Click on the field declaration, then go to menu:Refactor[Encapsulate fields...]. Set the visibility of accessors to `package-local`.

.. Do the same with field `isGranted` and `admin`.

. Move method `claimedBy()` to class `PermissionState`.
.. Select the body of the method, then go to menu:Refactor[Extract/Introduce > Method...].
.. Use a temporary name for the new method, for instance, `extracted()` or `extractedClaimedBy()`.
.. Click on the name of the extracted method and go to menu:Refactor[Move Instance Method...] and choose `PermissionState`.
.. After moving the method rename the method to `claimedBy()`.

. Now, repeat the previsous steps for methods `deniedBy()` and `grantedBy()`.
. Run all tests and check that they still pass after the changes.
. Commit and push your changes.
****

=== Replace Conditional with Polymorphism

Now, we will remove the state-related conditionals from the moved methods and place in each state subclass the part of method body related to it.

.To-Do
****
. In class `PermissionState`:
.. Push-down method `claimedBy()`
.. Create an abstract method with the same signature in class `PermissionState` to avoid accessibility errors.
.. Now, analyze all the pushed methods and remove the code that will never be executed.
.. For instance, the behavior of method `claimedBy()` is only executed when the state is _Requested_. Nothing is executed in other states.
+
[source,java]
.Method Requested::claimedBy(), after changes
----
void claimedBy(SystemAdmin admin, SystemPermission systemPermission) {
  systemPermission.willBeHandledBy(admin);
  systemPermission.setState(CLAIMED);
}
----
+
[source,java]
.Method Claimed::claimedBy(), after changes
----
void claimedBy(SystemAdmin admin, SystemPermission systemPermission) {
}
----

. Repeat the previous steps for methods `deniedBy()` and `grantedBy()`.
. Run all tests and check that they still pass after the changes.
. Commit and push your changes.
****

//== Questions


[bibliography]
== References

* [[[rtp, 1]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
From Journeyman to Master. Addison-Wesley. 1999.
